Repository the-control-group/voyager, pull requests merged in 2018-10, with the labels that each got.

#3629 Move docs to Gitbook
  .gitbook.yaml
  docs/.gitbook/assets/bread_details.png
  docs/.gitbook/assets/bread_fields.png
  docs/.gitbook/assets/bread_relationship.png
  docs/.gitbook/assets/bread_relationship_form.png
  docs/.gitbook/assets/bread_relationship_no_bread.png
  docs/.gitbook/assets/compass_1.png
  docs/.gitbook/assets/compass_2.png
  docs/.gitbook/assets/compass_3.png
  docs/.gitbook/assets/database-manager.png
  docs/.gitbook/assets/database_new_table.png
  docs/.gitbook/assets/media_manager.png
  docs/.gitbook/assets/menu_1.jpg
  docs/.gitbook/assets/menu_2.jpg
  docs/.gitbook/assets/role.png
  docs/.gitbook/assets/settings.png
  docs/.gitbook/assets/upgrade_menu_item.png
  docs/core-concepts/bread-builder.md
  docs/core-concepts/compass.md
  docs/core-concepts/database-manager.md
  docs/core-concepts/helper-methods.md
  docs/core-concepts/media-manager.md
  docs/core-concepts/menus-and-menu-builder.md
  docs/core-concepts/multilanguage.md
  docs/core-concepts/roles-and-permissions.md
  docs/core-concepts/routing.md
  docs/core-concepts/settings.md
  docs/customization/adding-custom-formfields.md
  docs/customization/additional-css-js.md
  docs/customization/custom-http-controllers.md
  docs/customization/custom-realtionship-attributes.md
  docs/customization/enabling-soft-delete.md
  docs/customization/overriding-routes.md
  docs/customization/overriding-views.md
  docs/customization/tinymce.md
  docs/getting-started/configurations.md
  docs/getting-started/installation.md
  docs/getting-started/upgrading.md
  docs/getting-started/what-is-voyager.md
  docs/introduction.md
  docs/summary.md
  docs/troubleshooting/missing-required-parameter.md
  docs/troubleshooting/using-https.md
Labels: documentation

#3361 Add support for Lithuanian language to slugify.js
  resources/assets/js/slugify.js
Labels: i18n

#3653 Fix #3646
  resources/views/tools/bread/edit-add.blade.php
Labels: bugfix

#3661 fix relationship edit-add.blade.php
  resources/views/bread/edit-add.blade.php
Labels: bugfix

#3658 Updated Turkish Language Files
  publishable/lang/tr/analytics.php
  publishable/lang/tr/bread.php
  publishable/lang/tr/compass.php
  publishable/lang/tr/database.php
  publishable/lang/tr/datatable.php
  publishable/lang/tr/dimmer.php
  publishable/lang/tr/error.php
  publishable/lang/tr/form.php
  publishable/lang/tr/generic.php
  publishable/lang/tr/login.php
  publishable/lang/tr/post.php
  publishable/lang/tr/profile.php
  publishable/lang/tr/seeders.php
  publishable/lang/tr/settings.php
Labels: i18n

#3692 'usage_help' syntax fix
  publishable/lang/pt/settings.php
Labels: i18n

#3674 Japanese language (ja) files
  publishable/lang/ja/analytics.php
  publishable/lang/ja/bread.php
  publishable/lang/ja/compass.php
  publishable/lang/ja/database.php
  publishable/lang/ja/datatable.php
  publishable/lang/ja/date.php
  publishable/lang/ja/dimmer.php
  publishable/lang/ja/error.php
  publishable/lang/ja/form.php
  publishable/lang/ja/generic.php
  publishable/lang/ja/json.php
  publishable/lang/ja/login.php
  publishable/lang/ja/media.php
  publishable/lang/ja/menu_builder.php
  publishable/lang/ja/post.php
  publishable/lang/ja/profile.php
  publishable/lang/ja/seeders.php
  publishable/lang/ja/settings.php
  publishable/lang/ja/theme.php
  resources/views/tools/bread/index.blade.php
Labels: i18n
