Repository the-control-group/voyager, pull requests merged in 2018-04, with the labels that each got.

#2914 Condition for permissions that don't exist fixed
  src/Policies/MenuItemPolicy.php
Labels: bugfix

#2885 Additional relationship attributes/accessors
  src/Http/Controllers/VoyagerDatabaseController.php
Labels: enhancement

#2886 Fix for spatial column type save error on mysq 5.7
  src/Http/Controllers/ContentTypes/Coordinates.php
Labels: bugfix

#2455 Address .login-sidebar properly for CSS overrule
  resources/views/login.blade.php
Labels: bugfix, design

#2912 English translation fixes
  publishable/lang/en/bread.php
  publishable/lang/en/database.php
  resources/views/bread/browse.blade.php
Labels: bugfix, i18n

#2889 Fix for spatial traits, wrong coordinates order in getCoordinates() function
  src/Traits/Spatial.php
Labels: bugfix

#2931 fix: belongsToMany relationships can now be removed
  src/Http/Controllers/Controller.php
Labels: bugfix

#2978 Fix BelongsToMany Taggable issue
  resources/views/tools/bread/relationship-partial.blade.php
Labels: bugfix

#1989 Feature/rtl support v1
  publishable/assets/css/rtl.css
  publishable/config/voyager.php
  resources/views/dashboard/navbar.blade.php
  resources/views/login.blade.php
  resources/views/master.blade.php
Labels: QA Needed

#2524 Fix for non-image files all being uploaded to the root in Media Manager
  src/Http/Controllers/VoyagerMediaController.php
Labels: QA Needed

#2994 Fix issue 2989
  resources/views/formfields/relationship.blade.php
Labels: bugfix

#3005 Fixing a broken URL
  resources/views/dashboard/sidebar.blade.php
Labels: bugfix

#3061 [testing] Add test for the AbstractAction class
  tests/Unit/Actions/AbstractActionTest.php
Labels: testing

#3082 Fix namespace naming conflict
  src/Translator.php
Labels: bugfix

#3095 Fix some spelling errors and add missing translations for Dutch language
  publishable/lang/nl/form.php
  publishable/lang/nl/menu_builder.php
  publishable/lang/nl/profile.php
Labels: i18n

#3100 Persian translation
  publishable/lang/fa/analytics.php
  publishable/lang/fa/bread.php
  publishable/lang/fa/compass.php
  publishable/lang/fa/database.php
  publishable/lang/fa/datatable.php
  publishable/lang/fa/date.php
  publishable/lang/fa/dimmer.php
  publishable/lang/fa/error.php
  publishable/lang/fa/form.php
  publishable/lang/fa/generic.php
  publishable/lang/fa/json.php
  publishable/lang/fa/login.php
  publishable/lang/fa/media.php
  publishable/lang/fa/menu_builder.php
  publishable/lang/fa/post.php
  publishable/lang/fa/profile.php
  publishable/lang/fa/seeders.php
  publishable/lang/fa/settings.php
  publishable/lang/fa/theme.php
Labels: i18n
