Repository the-control-group/voyager, pull requests merged in 2018-06, with the labels that each got.

#3274 Changing exception type for canOrFail
  src/Voyager.php
Labels: bugfix

#3289 Add missing fa translations
  publishable/lang/fa/bread.php
  publishable/lang/fa/database.php
  publishable/lang/fa/datatable.php
  publishable/lang/fa/form.php
  publishable/lang/fa/generic.php
  publishable/lang/fa/menu_builder.php
  publishable/lang/fa/seeders.php
  publishable/lang/fa/settings.php
Labels: i18n

#3280 Database-Tool default charset from config
  src/Http/Controllers/VoyagerDatabaseController.php
Labels: enhancement

#3257 Update generic.php
  publishable/lang/ru/bread.php
  publishable/lang/ru/database.php
  publishable/lang/ru/generic.php
  publishable/lang/ru/media.php
  publishable/lang/ru/post.php
  publishable/lang/ru/profile.php
Labels: i18n

#3324 GL translations updated
  publishable/lang/gl/analytics.php
  publishable/lang/gl/bread.php
  publishable/lang/gl/compass.php
  publishable/lang/gl/database.php
  publishable/lang/gl/error.php
  publishable/lang/gl/form.php
  publishable/lang/gl/generic.php
  publishable/lang/gl/media.php
  publishable/lang/gl/menu_builder.php
  publishable/lang/gl/post.php
  publishable/lang/gl/profile.php
  publishable/lang/gl/seeders.php
  publishable/lang/gl/voyager.php
Labels: i18n

#3348 Translation Improvements for Turkish
  publishable/lang/tr/analytics.php
  publishable/lang/tr/database.php
  publishable/lang/tr/datatable.php
  publishable/lang/tr/dimmer.php
  publishable/lang/tr/error.php
  publishable/lang/tr/form.php
  publishable/lang/tr/generic.php
  publishable/lang/tr/json.php
  publishable/lang/tr/media.php
  publishable/lang/tr/menu_builder.php
  publishable/lang/tr/post.php
  publishable/lang/tr/profile.php
  publishable/lang/tr/seeders.php
  publishable/lang/tr/settings.php
Labels: i18n

#3269 French Translation Updated
  publishable/lang/fr/analytics.php
  publishable/lang/fr/bread.php
  publishable/lang/fr/compass.php
  publishable/lang/fr/database.php
  publishable/lang/fr/datatable.php
  publishable/lang/fr/dimmer.php
  publishable/lang/fr/error.php
  publishable/lang/fr/form.php
  publishable/lang/fr/generic.php
  publishable/lang/fr/media.php
  publishable/lang/fr/post.php
  publishable/lang/fr/profile.php
  publishable/lang/fr/seeders.php
  publishable/lang/fr/settings.php
Labels: i18n
