Repository the-control-group/voyager, pull requests merged in 2018-08, with the labels that each got.

#3446 Fix czech translation
  publishable/lang/cs/analytics.php
  publishable/lang/cs/database.php
  publishable/lang/cs/datatable.php
  publishable/lang/cs/date.php
  publishable/lang/cs/dimmer.php
  publishable/lang/cs/error.php
  publishable/lang/cs/form.php
  publishable/lang/cs/generic.php
  publishable/lang/cs/json.php
  publishable/lang/cs/login.php
  publishable/lang/cs/media.php
  publishable/lang/cs/menu_builder.php
  publishable/lang/cs/post.php
  publishable/lang/cs/profile.php
  publishable/lang/cs/seeders.php
  publishable/lang/cs/settings.php
  publishable/lang/cs/theme.php
Labels: i18n

#3099 Various enhancements
  composer.json
  src/Commands/InstallCommand.php
  src/Http/Controllers/VoyagerBaseController.php
  src/Traits/Spatial.php
  tests/AlertTest.php
  tests/DatabaseTest.php
  tests/DisabledTestException.php
  tests/EventTest.php
  tests/LoginTest.php
  tests/Models/CategoryTest.php
  tests/Models/PageTest.php
  tests/Models/User.php
  tests/MultilingualTest.php
  tests/PermissionTest.php
  tests/RolesTest.php
  tests/RouteTest.php
  tests/SettingsTest.php
  tests/TestCase.php
  tests/UserProfileTest.php
  tests/ViewEventTest.php
  tests/migrations/2014_10_12_000000_create_users_table.php
  tests/migrations/2014_10_12_100000_create_password_resets_table.php
Labels: testing

#3117 Make sure that the required field always contains a boolean value
  src/Models/DataType.php
Labels: enhancement

#3288 Resizeable support for multiple images
  src/Traits/Resizable.php
Labels: enhancement

#3409 Create compass.php
  publishable/lang/ru/compass.php
Labels: i18n

#3391 Update menu_builder.php
  publishable/lang/fa/menu_builder.php
Labels: i18n

#3473 fix Undefined variable: path
  src/Http/Controllers/ContentTypes/File.php
Labels: bugfix

#3466 Create translation ru/seeders
  publishable/lang/ru/seeders.php
Labels: i18n

#3465 Fix translation error
  publishable/lang/pt_br/bread.php
  publishable/lang/pt_br/database.php
Labels: i18n

#3463 Fixed option «quality»
  src/Http/Controllers/ContentTypes/Image.php
Labels: bugfix
