Repository the-control-group/voyager, pull requests merged in 2018-03, with the labels that each got.

#2747 Correct tabindex on database/ select elements
  resources/views/tools/database/vue-components/database-column.blade.php
  resources/views/tools/database/vue-components/database-types.blade.php
Labels: bugfix

#2697 Use Carbon instead of gmdate (already)
  resources/views/formfields/date.blade.php
  src/Http/Controllers/ContentTypes/Timestamp.php
Labels: bugfix

#2730 Add missing settings translations
  publishable/lang/fr/voyager.php
  publishable/lang/pt/voyager.php
  publishable/lang/ru/voyager.php
  publishable/lang/tr/voyager.php
  publishable/lang/uk/voyager.php
  src/Http/Controllers/VoyagerSettingsController.php
Labels: locale

#2670 Fix for #1731
  resources/views/settings/index.blade.php
Labels: QA Needed

#2677 Fixes #2075 and #1949
  resources/views/bread/browse.blade.php
  resources/views/menus/browse.blade.php
  resources/views/tools/database/index.blade.php
Labels: QA Needed

#2775 Hotfix: Undefined property: Illuminate\Auth\AuthManager::$user
  src/Http/Middleware/VoyagerAdminMiddleware.php
Labels: bugfix

#2417 TimeHandler
  resources/views/formfields/time.blade.php
  src/FormFields/TimeHandler.php
  src/VoyagerServiceProvider.php
Labels: QA Needed, enhancement

#1885 Fix many queries to storage for get files info
  src/Http/Controllers/VoyagerMediaController.php
Labels: QA Needed, enhancement

#2780 adding browse_bread translation - RU
  publishable/lang/ru/voyager.php
Labels: locale

#2798 Fix Dropdowns not working with asian menu-titles
  resources/views/menu/admin_menu.blade.php
Labels: bugfix

#2804 Adding legend option to edit-create blade
  resources/views/bread/edit-add.blade.php
Labels: enhancement

#2808 Ui locale selection
  migrations/2018_03_11_000000_add_user_settings.php
  publishable/database/seeds/DataRowsTableSeeder.php
  publishable/lang/en/voyager.php
  resources/views/users/edit-add.blade.php
  src/Http/Middleware/VoyagerAdminMiddleware.php
  src/Models/User.php
  src/Voyager.php
  tests/UserProfileTest.php
Labels: feature

#2678 Add the ability to add custom actions buttons
  resources/views/bread/browse.blade.php
  resources/views/bread/partials/actions.blade.php
  src/Actions/AbstractAction.php
  src/Actions/ActionInterface.php
  src/Actions/DeleteAction.php
  src/Actions/EditAction.php
  src/Actions/ViewAction.php
  src/Voyager.php
  tests/RolesTest.php
Labels: QA Needed

#2838 Add missing Chinese translations
  publishable/lang/zh_CN/voyager.php
Labels: locale

#2830 Fix slugify
  resources/assets/js/slugify.js
Labels: bugfix

#2827 Order Bread Items
  migrations/2018_03_14_000000_add_details_to_data_types_table.php
  publishable/lang/de/bread.php
  publishable/lang/de/generic.php
  publishable/lang/en/bread.php
  publishable/lang/en/generic.php
  resources/views/bread/browse.blade.php
  resources/views/bread/order.blade.php
  resources/views/tools/bread/edit-add.blade.php
  routes/voyager.php
  src/Http/Controllers/VoyagerBaseController.php
  src/Models/DataType.php
Labels: enhancement

#2863 Fix migration role_id relationship
  migrations/2017_11_26_013050_add_user_role_relationship.php
Labels: bugfix

#2865 Ordering fix
  resources/views/tools/bread/edit-add.blade.php
Labels: bugfix

#2872 Fix pt br lang
  publishable/lang/pt_br/dimmer.php
Labels: locale

#2892 Delete Menu not working
  resources/views/menus/browse.blade.php
Labels: bugfix

#2891 Fix readlink invalid argument
  src/VoyagerServiceProvider.php
Labels: bugfix

#2915 Fixes password corruption on editing of a user. Fixes #2909
  src/Http/Controllers/ContentTypes/Password.php
Labels: bugfix
