Repository the-control-group/voyager, pull requests merged in 2018-02, with the labels that each got.

#2635 French Translation Update
  publishable/lang/fr/voyager.php
Labels: locale

#2622 Turkish Fix
  publishable/lang/tr/voyager.php
Labels: locale

#2425 mysql spatial functions are standardized to (lon, lat)
  src/Http/Controllers/ContentTypes/Coordinates.php
  src/Http/Controllers/Controller.php
Labels: refactor

#2671 Stop hardcoding body field type
  resources/views/posts/edit-add.blade.php
Labels: bugfix

#2659 support arabic
  resources/assets/js/slugify.js
Labels: locale

#2588 Test widgets
  tests/WidgetTest.php
  tests/rendered_widgets.html
Labels: testing

#2660 Fix BREAD Validation issues #1963 and #2179
  resources/assets/js/app.js
  resources/views/formfields/checkbox.blade.php
  resources/views/formfields/code_editor.blade.php
  resources/views/formfields/color.blade.php
  resources/views/formfields/coordinates.blade.php
  resources/views/formfields/date.blade.php
  resources/views/formfields/file.blade.php
  resources/views/formfields/hidden.blade.php
  resources/views/formfields/image.blade.php
  resources/views/formfields/markdown_editor.blade.php
  resources/views/formfields/multiple_images.blade.php
  resources/views/formfields/number.blade.php
  resources/views/formfields/radio_btn.blade.php
  resources/views/formfields/rich_text_box.blade.php
  resources/views/formfields/select_dropdown.blade.php
  resources/views/formfields/select_multiple.blade.php
  resources/views/formfields/text.blade.php
  resources/views/formfields/text_area.blade.php
  resources/views/formfields/timestamp.blade.php
  src/Http/Controllers/Controller.php
Labels: QA Needed

#2687 Add polish translation
  publishable/lang/pl/voyager.php
Labels: locale

#2675 Fixing moving file to folder
  src/Http/Controllers/VoyagerMediaController.php
Labels: QA Needed

#2700 Fix 'z-index' on search form
  resources/assets/sass/app.scss
  resources/views/bread/browse.blade.php
Labels: bugfix

#2722 Adding missing voyager namespace to i18n references
  resources/views/posts/edit-add.blade.php
  resources/views/tools/bread/index.blade.php
  src/Http/Controllers/VoyagerBaseController.php
  src/Http/Controllers/VoyagerBreadController.php
Labels: bugfix, locale

#2729 Fix 'testWidgetRenders' on Windows
  tests/WidgetTest.php
Labels: enhancement, testing

#2725 [FIX] Not enough argument on Controller@getContentBasedOnType.
  src/Http/Controllers/Controller.php
  tests/SettingsTest.php
Labels: bugfix

#2733 Re #2287: Cover Image Upload Field Accepts Non-Image Filetypes
  resources/views/formfields/image.blade.php
  resources/views/formfields/multiple_images.blade.php
Labels: bugfix, enhancement

#2736 Remember settings tab
  resources/views/settings/index.blade.php
  src/Http/Controllers/VoyagerSettingsController.php
Labels: enhancement
