Repository the-control-group/voyager, pull requests merged in 2018-12, with the labels that each got.

#3720 Add: Kurdish Language (ku) files
  publishable/lang/ku/analytics.php
  publishable/lang/ku/bread.php
  publishable/lang/ku/compass.php
  publishable/lang/ku/database.php
  publishable/lang/ku/datatable.php
  publishable/lang/ku/date.php
  publishable/lang/ku/dimmer.php
  publishable/lang/ku/error.php
  publishable/lang/ku/form.php
  publishable/lang/ku/generic.php
  publishable/lang/ku/json.php
  publishable/lang/ku/login.php
  publishable/lang/ku/media.php
  publishable/lang/ku/menu_builder.php
  publishable/lang/ku/post.php
  publishable/lang/ku/profile.php
  publishable/lang/ku/seeders.php
  publishable/lang/ku/settings.php
  publishable/lang/ku/theme.php
Labels: i18n

#3621 added listener for bread delete for menu and permission removal
  src/Listeners/DeleteBreadMenuItem.php
  src/Providers/VoyagerEventServiceProvider.php
Labels: QA Needed

#3797 Fix exception language string
  src/Traits/AlertsMessages.php
Labels: i18n

#3620 Fix drop down multilevel admin menu
  resources/assets/js/app.js
Labels: QA Needed

#3754 Fix bug#
  publishable/assets/css/rtl.css
Labels: QA Needed, design

#3547 #3350 - restore the ability to empty a multi select
  src/Http/Controllers/ContentTypes/Relationship.php
Labels: QA Needed
