Repository the-control-group/voyager, pull requests merged in 2018-09, with the labels that each got.

#3334 Update Datetime Picker
  package.json
  resources/assets/js/app.js
  resources/assets/sass/app.scss
Labels: bugfix

#3525 Switch to using Intervention Image facade
  src/Http/Controllers/VoyagerMediaController.php
Labels: enhancement

#3526 Remove extra curly-braces
  resources/views/posts/edit-add.blade.php
Labels: bugfix

#3588 Update to spanish generic.php
  publishable/lang/es/generic.php
Labels: i18n
