Repository the-control-group/voyager, pull requests merged in 2020-01, with the labels that each got.

#4680 Modify typos: priveleges to privileges
  docs/getting-started/installation.md
Labels: documentation

#4687 Fix #4685
  resources/views/media/manager.blade.php
Labels: bugfix

#4686 Changed example
  docs/bread/introduction.md
Labels: documentation

#4649 Fix upload file removing previous
  src/Http/Controllers/Controller.php
  tests/BreadMediaUploadTest.php
Labels: bugfix

#4559 Enhance Widget Layout
  resources/views/dimmers.blade.php
  src/Voyager.php
  tests/Unit/VoyagerTest.php
Labels: QA Needed

#4497 Add Vietnamese Language
  publishable/lang/vi/analytics.php
  publishable/lang/vi/bread.php
  publishable/lang/vi/compass.php
  publishable/lang/vi/database.php
  publishable/lang/vi/datatable.php
  publishable/lang/vi/date.php
  publishable/lang/vi/dimmer.php
  publishable/lang/vi/error.php
  publishable/lang/vi/form.php
  publishable/lang/vi/generic.php
  publishable/lang/vi/json.php
  publishable/lang/vi/login.php
  publishable/lang/vi/media.php
  publishable/lang/vi/menu_builder.php
  publishable/lang/vi/post.php
  publishable/lang/vi/profile.php
  publishable/lang/vi/seeders.php
  publishable/lang/vi/settings.php
  publishable/lang/vi/theme.php
Labels: i18n

#4718 Intervention from Laravel5 to Laravel Recent
  docs/getting-started/installation.md
Labels: documentation
