Repository the-control-group/voyager, pull requests merged in 2020-04, with the labels that each got.

#4716 Fix save bread when ajax calls are not done
  resources/views/tools/bread/edit-add.blade.php
  resources/views/tools/bread/relationship-new-modal.blade.php
  resources/views/tools/bread/relationship-partial.blade.php
Labels: QA Needed, bugfix

#4727 Enable customization of TinyMCE init options
  docs/bread/formfields/tinymce.md
  docs/customization/tinymce.md
  docs/getting-started/upgrading.md
  docs/summary.md
  resources/assets/js/app.js
  resources/assets/js/voyager_tinymce.js
  resources/assets/js/voyager_tinymce_config.js
  resources/views/formfields/rich_text_box.blade.php
  resources/views/settings/index.blade.php
Labels: feature

#4859 Fix belongstomany with custom keys
  docs/bread/relationships.md
  resources/views/formfields/relationship.blade.php
  src/Http/Controllers/Controller.php
Labels: bugfix

#4862 Populate select lists when opening details
  resources/views/tools/bread/edit-add.blade.php
Labels: enhancement

#4782 Fix of BUG
  src/Http/Controllers/VoyagerBaseController.php
Labels: QA Needed

#4870 Fix relationships pagination repeating None
  src/Http/Controllers/VoyagerBaseController.php
Labels: enhancement

#4869 Fix redirect to browse not working with scopes
  src/Http/Controllers/VoyagerBaseController.php
Labels: bugfix

#4884 Fix additional attribute not listed
  resources/views/tools/bread/edit-add.blade.php
Labels: bugfix
