Repository the-control-group/voyager, pull requests merged in 2020-05, with the labels that each got.

#4922 Fix validation for array elements
  src/Http/Controllers/Controller.php
Labels: bugfix

#4937 Fix filter null values when array does not start with 0
  src/Http/Controllers/ContentTypes/Relationship.php
Labels: bugfix, enhancement

#4901 Fix slugify.js not replacing to empty string
  resources/assets/js/slugify.js
Labels: bugfix

#4955 Fix translations loaded when not needed
  src/Traits/Translatable.php
Labels: enhancement
